brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('todos.urls')),
    # path('', lambda request: redirect('todo_list_list'), name='home'),  # Redirect to todo_list_list
    path('todos/', include('todos.urls')),  # Include the todos app URLs
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    # Feature 7: List view for TodoList
    path('', views.todo_list_view, name='todo_list_list'),

    # Feature 8: Detail view for a specific TodoList
    path('<int:id>/', views.todo_list_detail_view, name='todo_list_detail'),

    # Feature 9: Create view for a new TodoList
    path('create/', views.todo_list_create_view, name='todo_list_create'),

    # Feature 10: Update view for an existing TodoList
    path('<int:id>/edit/', views.todo_list_update_view, name='todo_list_update'),

    # Feature 11: Delete view for an existing TodoList
    path('<int:id>/delete/', views.todo_list_delete_view, name='todo_list_delete'),

    # Feature 12: Create view for a to-do list item
    path('items/create/', views.todo_item_create_view, name='todo_item_create'),

    # Feature 13: Create view for item update
    path('items/<int:id>/edit/', views.todo_item_update_view, name='todo_item_update'),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True, null=True)

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)

    list = models.ForeignKey("TodoList", on_delete=models.CASCADE, related_name="items")

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from .models import TodoList

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoList, TodoItem
from .forms import TodoListForm


# Create your views here.
def todo_list_update_view(request, id):
    todo_lists = get_object_or_404(TodoList, id=id)
    if request.method == 'POST':
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_deatail', id=todo_list.id)
    form = TodoListForm(instance=todo_list)
    context = {'form': form, 'todo_list': todo_list}
    return render(request, 'todo/todo_list_update.html', context)

def todo_list_view(request):
    todo_lists = TodoList.objects.all()
    context = {
        'todo_lists': todo_lists,
    }
    return render(request, 'todos/todo_list.html', context)

def todo_list_detail_view(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    return render(request, 'todos/todo_list_detail.html', {'todo_list': todo_list})

def todo_list_create_view(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect("todo_list_detail", id=todo_list.id)
    else:
        form = TodoListForm()
    return render(request, 'todos/todo_list_create.html', {'form': form})

def todo_list_delete_view(request, id):
    todo_list = get_object_or_404(TodoList, id=id)

    if request.method == 'POST':
        todo_list.delete()
        return redirect('todos:todo_list_list')

    context = {'todo_list': todo_list}
    return render(request, 'todos/todo_list_delete.html', context)

def todo_item_create_view(request):
    if request.method == 'POST':
        form = TodoItemForm(request.POST)
        if form.is_valid():
            todo_item = form.save(commit=False)
            todo_item.list = TodoList.objects.get(id=request.POST['list'])
            todo_item.save()  # Save the TodoItem
            return redirect("todo_list_detail", id=todo_item.list.id)
    else:
        form = TodoItemForm()

    context = {
        'form': form,
    }
    return render(request, 'todos/todo_item_create.html', context)

def todo_item_update_view(request, id):
    item = get_object_or_404(TodoItem, id=id)
    if request.method == 'POST':
        form = TodoItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('todo_list_detail', id=item.list.id)
    else:
        form = TodoItemForm(instance=item)
    return render(request, 'todos/todo_item_update.html', {'form': form, 'item': item})

todos/templates/todos/todo_item_create.html
{% extends "todo_list.html" %}

{% block content %}
  <div>
    <h1>Create a new item</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <p><a href="{% url 'todo_list_detail' id=form.instance.list.id %}">Back to List</a></p>
{% endblock %}

todos/templates/todos/todo_item_update.html
{% extends 'todo_list.html' %}

{% block content %}
<main>
    <div>
        <h1>Update item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_list %}
                    <tr>
                        <td><a href="{% url 'todo_list_detail' id=todo_list.id %}">{{ todo_list.name }}</a>
                        <td><a href="{% url 'todo_list_create' %}">Create a new list</a>
                        {{ todo_list.items.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_create.html
{% extends "todo_list.html" %}

{% block content %}
<main>
    <div>
        <h1>Create a new list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock %}

todos/templates/todos/todo_list_delete.html
{% extends "todo_list.html" %}

{% block content %}
    <div>
        <h1>Are you sure?</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

todos/templates/todos/todo_list_detail.html
{% extends "todo_list.html" %}

{% block content %}
    <main>
        <div>
            <h1>{{ todo_list.name }}</h1>
            <p><a href="{% url 'todos:todo_list_update' id=todo_list.id %}">Edit</a></p>
            <p><a href="{% url 'todos:todo_list_delete' id=todo_list.id %}">Delete</a></p>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todo_list.items.all %}
                    <tr>
                        <td><a href="{% url 'todo_item_update' id=item.id %}">{{ item.task }}</a></td>
                        <td>{{ item.due_date }}</td>
                        <td>
                            <a href="{% url 'todo_item_update' id=item.id %}">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock %}

todos/templates/todos/todo_list_update_view.html
<!-- todos/todo_list_update.html -->
{%extends "todo_list.html" %}

{% block content %}
    <div>
        <h1>Update List</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
        </form>
    </div>
{% endblock %}